### ISSUE TITLE
How to run the benchmark locally

### ISSUE THREAD

**Issue by xania** [modderme123/js-reactivity-benchmark#3]
Hi, I cloned the repository locally so that I can try out the benchmark on my machine, 
- what are the steps to install everything? npm install?
- how do I apply the angular patch? git apply ./patches/.....patch? does the working dir matters from which to run the command?
- how to run the application after install? node ./src/index.ts? npx tsx ./src/index.ts? when I try I only see "Assertion failed" messages in my console

thx

**Comment by modderme123** [comment]
Running `pnpm i` (you may need to first run `curl -fsSL https://get.pnpm.io/install.sh | sh -` to install pnpm) will automatically install and patch, then `pnpm bench`

**Comment by xania** [comment]
> Running `pnpm i` (you may need to first run `curl -fsSL https://get.pnpm.io/install.sh | sh -` to install pnpm) will automatically install and patch, then `pnpm bench`

_pnpm i_ worked, it apparently applies the patch automatically I didnt know about that. Now `pnpm bench` also runs

**Comment by xania** [comment]
One more question, is there an easy way to generate the graphs after completion of the run?

**Comment by modderme123** [comment]
Yes, I'm working on a command to do this automatically (using something like https://observablehq.com/@d3/grouped-bar-chart) but these graphs were generated by:

1. pasting the data into a .csv file
2. uploading that file to a new public tableau project
3. clicking sheet1
4. dragging in test and then framework into rows, and time into columns

**Comment by xania** [comment]
One more thing, I've built an implementation based on observable pattern, which fits better with xania view library that I wrote than signals pattern. What really matters is internal graph algorithm, that's key for performance characteristics, less so whether signals or observables are on the surface, so I am looking to learn from other Libraries, first step is to be able to measure 
Here is my problem 
The benchmark assumes signals which makes it hard / unfair comparison for libraries based on observable pattern.
Would you consider extending the benchmark to support signals and observables? I don't mind putting in the work myself

**Comment by modderme123** [comment]
I'm curious what that would look like, but one of the nice things about using signals is the standard api which makes it easy to add new benchmarks, which I fear would be hurt by adding a different pattern if you have to write every benchmark in two ways. I wonder if it is possible to write a wrapper around observable based libraries like https://github.com/kosich/rxjs-autorun instead?

**Comment by xania** [comment]
I will give that a shot, I am sure it will come with a perf cost but we will see;)
